// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from here (not package.json's
    // `prisma.seed`, which is the pre-7 convention — kept below too for
    // discoverability/documentation, but this is what `prisma db seed`
    // actually executes). Uses `tsx` since Prisma's TS schema/config
    // tooling doesn't include a TS runner for arbitrary scripts.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
